name: send_email

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - name: test-send-mail
        run: echo "test send mail"
