name: send_email

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: test-send-mail
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python send_mail.py
